### PR TITLE
Add 'deploy' alias for 'publish'

### LINKED ISSUE #1739: Add `wrangler deploy`
#### Overview and problem statement

Brief explanation of the requested feature, and a description of the problem it would solve.

Many people  — including myself — have found `wrangler publish` to be an unintuitive way to deploy scripts. `wrangler deploy` is much more intuitive. Adding this as an alias or making that command print something out like `did you mean wrangler publish?` would be an easy improvement to make usability a little better.

### PR DESCRIPTION
**Pull request by ObsidianMinor**
I've always wanted this tbh.

Closes #1739

### CODE REVIEW

**Comment by ObsidianMinor** [comment]
rebased

**Review by xtuc — APPROVED** [review]
I agree that it's a better name for it

**Comment by xtuc** [comment]
Would you mind changing the README and adding a note to the changelog?

**Comment by Electroid** [comment]
Do we want to do this quite yet? `publish` does a build + deploy, but there have been talks previously to have `deploy` not build since it's not-obvious that it re-builds. If we alias this now, it will be complicated to fix later.

**Comment by xortive** [comment]
I agree with @Electroid, #1102 has some previous discussion here, and with the custom builds/modules PR landing soon I think adding a deploy or upload command that doesn't build makes a lot of sense.

Another thing to think about is "publish" really encompasses 3 steps currently, not 2:

- building your project into a workers script
- uploading the script to the API
- configuring how your script can be run such as routes, cron triggers, or implementing durable object namespace

These three steps to me would have commands like `wrangler build`, `wrangler upload`, and `wrangler deploy`, with `wrangler publish` being the shortcut version for when you want all three.

**Comment by ObsidianMinor** [comment]
Why offer a separate command to skip builds instead of a CLI option like `--skip-build`. The CLI option is more obvious since `deploy` and `publish` are effectively synonyms.

**Comment by Electroid** [comment]
We need to support `deploy`, but for the above reasons, I think we'll need more design before adding the alias.

**Pull request closed without merging**
