### PR TITLE
fix console formatting

### LINKED ISSUE #1707: console.log logs ConsoleAPICalled instead in 1.12.3
### 🐛 Bug Report
`console.log` doesn't log the right content but instead the ConsoleAPICalled

#### Environment
* operating system: Windows 10
* output of `node -v`: v12.16.3
* output of `wrangler -V`: wrangler 1.12.3

#### Steps to reproduce
- Update from wrangler 1.12.2 to 1.12.3
- Use Webpack type in wrangler.toml
- Write a console.log("A beautiful log") in your script
- Run it

#### Steps to fix
Downgrade from wrangler 1.12.3 to 1.12.2

#### What did you expect to see?
I expected to see the log "A beautiful log" in the console.

#### What did you see instead?
I saw "`ConsoleAPICalled(Event { type: "log", args: [RemoteObject { type: String, subtype: None, description: None, class_name: None, value: Some(String("My beautiful log")), preview: None }] })`" instead.

### PR DESCRIPTION
**Pull request by mdycz**
Fixes #1707

### CODE REVIEW

**Review by ags799 — APPROVED** [review]
Works on my machine, thanks!

**Review by xtuc — APPROVED** [review]

**Comment by xtuc** [comment]
would you mind adding a test to avoid future regressions?

**Comment by mdycz** [comment]
Sure, I'll get to it this weekend.

**Comment by mdycz** [comment]
I gave it a go, but my lack of experience with Rust makes it harder than it should be. I'm trying to unit test this function:
```rust
async fn print_ws_messages(
    mut read: SplitStream<WebSocketStream<Stream<TcpStream, TlsStream<TcpStream>>>>,
) -> Result<(), failure::Error> {
    ...
}
```
but couldn't find anything on mocking the SplitStream. I was thinking about mocking the whole WebScoketStream and splitting it, something similar to what's done in `listen` function - but can't figure out how to mock WebSocketStream without actual devtools port to connect to. Any tips or ideas?

**Comment by xortive** [comment]
I'll take a shot at adding this test over quick wins week, but we should get this in for the next release.

**Comment by mdycz** [comment]
I'd love to see the implementation to see how it's done, could you tag me in the PR?

**Pull request merged**
