### PR TITLE
[WIP] 🥌 make the installer work

### PR DESCRIPTION
**Pull request by ashleygwilliams**

### CODE REVIEW

**Comment by xtuc** [comment]
Once this lands, I can add the npm option on the website.

**Comment by ashleymichal** [comment]
for those picking this up: https://github.com/rustwasm/wasm-pack/tree/master/src/install

**Comment by EverlastingBugstopper** [comment]
Can we close this? @ashleygwilliams

**Comment by ashleygwilliams** [comment]
i'd say no. i would still like us to do this! it would be a good option for installation and nearly all the work is done.

**Comment by EverlastingBugstopper** [comment]
Does this PR touch anything other than docs? It's been sitting for a while and I'm wondering if we should close this (as it doesn't seem to touch anything but the docs). I think we want to have an issue tracking everything that it would take for wrangler to have its own installer as this is quite ambiguous.

**Comment by EverlastingBugstopper** [comment]
im closing this

**Comment by seanmorris** [comment]
Is this fixed yet? Still cannot install with npm.

**Comment by EverlastingBugstopper** [comment]
@seanmorris this PR is not related to the npm installer. could you please open a new issue with steps to reproduce the unwanted behavior you're seeing?

**Pull request closed without merging**
