### PR TITLE
WIP: open browser on wsl

### LINKED ISSUE #840: WSL preview doesn't open browser, maybe print URL to terminal window as workaround?
#### Environment

* operating system: Windows 10 build 19013
* output of `rustc -V`: rustc 1.36.0
* output of `node -v`: v12.10.0
* output of `wrangler -V`: wrangler 1.5.0

#### Steps to reproduce
`$ wrangler preview --watch`
or
`$ wrangler preview`

#### What did you expect to see?
A browser opening

#### What did you see instead?
First, thank you very much for making this 🙏🏻, it's really a joy to have a tool like this. 🙌🏻 I use it both on my Mac and Windows, but I'm reporting this bug/feature request as a Windows user.

The browser doesn't open. While WSL2 doesn't have xdg-open like the Linux variants, you can open the default browser using cmd.exe because of interop with Windows.

Alt text

So a command of:
**$ cmd.exe /c start http://example.com?foo=bar** would work on WSL2 environment.

Also printing --verbose doesn't print the URL either.
Alt text

I do hope you add this 🙏🏻. Also maybe an interim, have the preview URL printed, so I can copy and paste manually on the browser?

### PR DESCRIPTION
**Pull request by thisguychris**
fixes #840

### CODE REVIEW

**Comment by thisguychris** [comment]
Here's what I have so far, 

It does go to the correct conditional (printing `wsl`), but when I try to invoke `cmd.exe`. Interop seems not to work and cannot find cmd.exe, I tried referencing it directly via /mnt/ to no avail.

If I do invoke `xdg-open`, it does call it since rust treats it as Linux. So I'm not sure what to do at this point. But ultimately, I hope we can make it easier for WSL users to work out of the box.

**Comment by EverlastingBugstopper** [comment]
> If I do invoke xdg-open, it does call it since rust treats it as Linux. So I'm not sure what to do at this point. 

Does it open the browser?

> But ultimately, I hope we can make it easier for WSL users to work out of the box.

I'm hoping that [this feature](https://github.com/cloudflare/wrangler/pull/883) will essentially make `wrangler preview` obsolete and should work out of the box with WSL. I have some testing instructions on that branch if you'd like to play around with it :)

**Comment by thisguychris** [comment]
hey @EverlastingBugstopper sorry I missed this! 🤦🏻‍♂️ I would love to test that branch, is it [this?](https://github.com/cloudflare/wrangler/tree/avery/a-time-sync)

> Does it open the browser?
For `xdg-open` it does open a browser If you set the $BROWSER variable, (one caveat with windows is `xdg-open` doesn't work if the path has spaces on it, even if you escaped it.

So it's either you 1) have it installed outside of Program Files, like "C:\tools\firefox.exe" or 2) just make a symbolic link to the exe.). PR on the way 🔜 for the docs.

**Comment by EverlastingBugstopper** [comment]
That's the correct feature branch, but my latest work is [here](https://github.com/cloudflare/wrangler/tree/avery/websockets)

**Comment by ashleygwilliams** [comment]
closing in favor of a docs fix!

**Pull request closed without merging**
