### PR TITLE
update binary-install to avoid vulnerable axios version

### PR DESCRIPTION
**Pull request by simonhaenisch**
Fixes

```
                       === npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Server-Side Request Forgery                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.21.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @cloudflare/wrangler [dev]                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @cloudflare/wrangler > binary-install > axios                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1594                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

see https://github.com/EverlastingBugstopper/binary-install/releases/tag/v0.1.1

### CODE REVIEW

**Review by xtuc — APPROVED** [review]
thanks

**Review by nataliescottdavidson — APPROVED** [review]

**Comment by TrySound** [comment]
The latest binary-install also smaller
https://packagephobia.com/result?p=binary-install@0.0.1

**Comment by simonhaenisch** [comment]
@xtuc @nataliescottdavidson what's the plan on getting this merged? Any action needed from me?

**Comment by xtuc** [comment]
@simonhaenisch  sorry i just noticed that we have a `npm-shrinkwrap.json` here. could you please update it too?

**Comment by simonhaenisch** [comment]
Ah yup sorry I missed that, cause I did the edit via the Github editor 😅 done

**Review by xtuc — APPROVED** [review]

**Pull request merged**
