### PR TITLE
dont install wasm-pack for webpack type projects

### LINKED ISSUE #745: don't install wasm-pack for webpack projects
#### Environment

* operating system: macOS Mojav 10.14.6
* output of `rustc -V`: rustc 1.38.0 (625451e37 2019-09-23)
* output of `node -v`:
* output of `wrangler -V`: 👷 ✨  wrangler 1.4.0

#### Steps to reproduce

I have a static site generated from Hugo and am attempting to publish with Wrangler. It worked the first few times, but timed out trying to get to crates.io

#### What did you expect to see?

Publish success

#### What did you see instead?

`Total in 30 ms
C02WF0XWHV2R:blog-samrhea samrhea$ wrangler publish
🌀  Using namespace for Workers Site "__blog-samrhea-workers_sites_assets"
💁  ignoring file .DS_Store
💁  ignoring file .DS_Store
💁  Uploading...
✨  Success
⬇️ Installing wranglerjs...
Error: https://crates.io/api/v1/crates/wasm-pack: error trying to connect: connect timed out`

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**
fixes #745 

if folks want to use wasm-pack-plugin or some other tool, they should install and manage the necessary dependencies to do so. wrangler should only vendor what we know we need for the default use cases.

also we claimed to fix this in the 1.7.0 changelog and didn't actually do it

### CODE REVIEW

**Comment by ispivey** [comment]
Whoo! 🎉

**Comment by xtuc** [comment]
This was initally made to simplify using rustwasm with webpack, it's a breacking change but since nobody complained (as far as I know) I guess nobody uses it. I still think we should install it from users because it's simpler.

To avoid installing it for every webpack project, we can detect in wranglerjs if the webpack configuration uses the wasm-pack plugin

**Comment by EverlastingBugstopper** [comment]
@xtuc - didn't we make wasm-pack-plugin do the installation for you instead? I dont think that logic belongs in wrangler

**Comment by xtuc** [comment]
As far as I can remember wasm-pack plugin used to do the installation before we introduced it in wrangler and I'm unsure why we needed to.

**Comment by EverlastingBugstopper** [comment]
🤷

**Pull request merged**
