### PR TITLE
use --openssl-legacy-provider flag when running node 17

### LINKED ISSUE #2108: Wrangler is not compatible with Node.js 17 / OpenSSL 3.0
#### Describe the bug

Node.js 17 was released today and brings OpenSSL 3.0 support. [The Node.js 17 release notes mention potential cases where `ERR_OSSL_EVP_UNSUPPORTED` errors may occur](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md#openssl-30), and that is what is happening here.

#### Reproduce the bug

1. [Install Node.js 17](https://nodejs.org/en/)
2. Run `wrangler publish`
3. See error
```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\Eaton\AppData\Local\.wrangler\wranglerjs-1.19.4\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
#### Expected behavior

No error should occur, and the publish command should succeed.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Windows 10 x64
* output of `wrangler -V`: wrangler 1.19.4
* output of `node -v`: v17.0.0
* content of `wrangler.toml`: (should not be needed in this case)

### PR DESCRIPTION
**Pull request by caass**
Closes #2108

Node 17 uses openssl 3 by default, which is not
compatible with webpack 4. This change adds a check to see if
the user is running node 17, and if they are, we add the appropriate
flag to the call to node (https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md#openssl-30)

### CODE REVIEW

**Comment by Electroid** [comment]
What if we just always pipe this argument? Will node complain that it does not exist in older versions?

**Comment by threepointone** [comment]
node throws on bad options, so the check is required.

**Review by threepointone — APPROVED** [review]
approving, but looks like you'll have to fix the RUSTESCs as well. Feel free to merge this in if you're doing those soon.

**Comment by artob** [comment]
Note that this feature is causing a lot of trouble for some, including with Homebrew on macOS and with Arch Linux: https://github.com/cloudflare/wrangler/issues/2155#issuecomment-996678947

To quote https://github.com/cloudflare/wrangler/issues/2155#issuecomment-992264119:

> It looks like wrangler makes an assumption for a key openssl-legacy-provider based on nodejs version, but the heuristic is a bit more complex.

**Pull request merged**
