### PR TITLE
fix installer

### LINKED ISSUE #1234: Wrangler is not installed properly in gitlab ci through npm
#### Environment

* operating system: gitlab ci node:12
* output of `rustc -V`:
* output of `node -v`:v12.16.3
* output of `wrangler -V`:
* contents of `wrangler.toml`

#### Steps to reproduce
- Create a package.json with @cloudflare/wrangler as a dep
Create an .gitlab-ci.yml with the following content
```
image: node:12

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn config set cache-folder .yarn

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn
    - wrangler
```

#### What did you expect to see?
- The build should work correctly

#### What did you see instead?
```
 /node_modules/binary-install/src/binary.js:60
       throw `You have not installed ${this.name ? this.name : "this package"}`;
       ^
You have not installed wrangler
 (Use `node --trace-uncaught ...` to show where the exception was thrown)
 Task completed in 0m0.096s
Running after_script
00:01
Uploading artifacts for failed job
00:02
 ERROR: Job failed: exit code 1
```

### LINKED ISSUE #1286: Install Wrangler in local node_modules by default
#### Overview and problem statement

Current install directory is `join(os.homedir(), ".wrangler");`.

`homedir()` is blocked by many CI/CD tools (I tried on Vercel and Gatsby Cloud) which means you can't install anything there. Usually, if you run `npm i <package>` it installs in local `node_modules` - you can use different versions of packages safely in different projects. A package should install globally if you run `npm i -g <package>` command.

### LINKED ISSUE #1758: npm install: 3 high severity vulnerabilities
Vulnerabilites report from `npm install`:

```
$ npm i @cloudflare/wrangler -g

added 34 packages, and audited 35 packages in 14s

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

node & npm version

```
$ node --version
v15.5.0
$ npm --version
7.3.0
```

### LINKED ISSUE #1772: Incorrect Version Number
#### Environment

* operating system: macOS Big Sur V. 12.2.1
* output of `rustc -V`: rustc 1.49.0 (e1884a8e3 2020-12-29)
* output of `node -v`: v14.15.1
* output of `wrangler -V`: wrangler 1.12.2 (This is incorrect) [Should be 1.13.0]
* contents of `wrangler.toml` N/A

#### Steps to reproduce

1. Run `npm uninstall -g @cloudflare/wrangler && sudo npm install -g @cloudflare/wrangler@latest`
2. Run `wrangler -V`

#### What did you expect to see?
Output the correct version number (1.13.0 as of 18 Feb, 2021)

#### What did you see instead?
An old version number (1.12.2)

Screenshot 2021-02-18 at 13 26 42

Thank you.

### PR DESCRIPTION
**Pull request by xortive**
binary-install@0.1.1 broke semver, this PR changes our installer to use a cloudflare-owned version of binary-install with updated dependencies to resolve the previous vulnerability warnings from the old version of axios that was being used.

Question: should we re-publish wrangler@1.13.0 with the fixed installer, or just proceed to 1.14.0?

closes #1772 
closes #1286
closes #1234
closes #1758

### CODE REVIEW

**Review by xtuc — APPROVED** [review]

**Comment by koeninger** [comment]
1.14.0 makes more sense to me... did you have a reason to prefer re-publishing?

**Comment by xortive** [comment]
to not leave a broken version on npm is all

**Comment by xortive** [comment]
looks like `npx wrangler` now works as expected, using the version inside `node_modules` instead of `.wrangler`. future work could allow project-local configuration instead of using the `.wrangler` when wrangler is installed in this fashion.

unfortunately, it seems like the 1.13.0 binary is exiting with status code 1 despite printing no errors, so npx prints a scary error message after running a wrangler command...

**Review by Electroid — APPROVED** [review]
:rocket:

**Pull request merged**
