### PR TITLE
refactor: restructure cli into modularity

### PR DESCRIPTION
**Pull request by ericdeansanchez**
Hello All!

I was hoping to start a discussion about making some changes to the structure of the code that defines `wrangler`'s cli.

### Motivation
This PR was motivated by the size and composition of `main.rs`. My hope for this PR is that it improves:
- readability
- extensibility
- maintainability

Conceptually, `wrangler` has nine "root" sub-commands: `init`, `config`, the `kv` _suite_, etc. These commands have been broken up into separate modules (e.g. config -> `config.rs`) and then
aggregated under the `cli` module.

This reduces the size of `main.rs` (for readability)––it also separates some of the app configuration from app logic. I think this could be beneficial as certain portions of the cli grow (i.e. help & usage messages).

### Changes
These changes do not conflict with or change the public cli api (they are consistent with all tests invoked via `cargo test`).

However, the most notable changes are:
- the introduction of `KvSubcommandArgs`
- the encapsulation about-messages within their respective sub-commands
- the encapsulation of top-level `wrangler` commands
- the introduction of the `cli_prelude.rs` module

### Notes
`KvSubcommandArgs` eliminates ~21 calls to `clone()`. Moreover, if future arguments need to be added or removed to individual sub-sub-commands this reduces the chances of forgetting one.

The encapsulation of about-messages within sub-commands is a result of breaking up the cli components. I basically did what `console::Emoji` does under the hood to individual emojis but to the entire about-message portion to avoid introducing manual lifetime handling. This change also removes calls to `&*format(...)`.

### CODE REVIEW

**Comment by parkerduckworth** [comment]
Is there any downside to these changes? 

The modularization of `main` provides significant improvements in readability and likely maintainability, but there may be something I'm not seeing.

Any thoughts @EverlastingBugstopper @ashleymichal ?

**Comment by ashleymichal** [comment]
hey @parkerduckworth thanks so much for the PR, there's some great stuff here!

bigger restructures like this are hard to put in on the fly; we need to get consensus from the team, keep the PR abreast of ongoing prioritized feature work, code review it, and update other feature branches, etc.

A lot of the team is already/about to be out for the holiday season, so it is likely we will not get around to those steps until after New Year, but I wanted to touch base and let you know that we see and appreciate this PR!

**Comment by parkerduckworth** [comment]
@ashleymichal Yeah I totally understand!  Thanks for your reply, I'm looking forward to seeing where this goes @ericdeansanchez 

Happy Holidays

**Comment by ashleymichal** [comment]
oop! i mixed up the author with the commenter. sorry about that, and thanks @ericdeansanchez for the PR!

**Comment by ericdeansanchez** [comment]
It's been a hot minute since I opened this PR; I just got the notification from the Stale bot. 

_Revisiting this PR:_
IIRC this was meant to be somewhat of a cosmetic change. The thought was that command customization usually results in a proportional increase in file length. Instead of growing `main.rs`, commands can be pulled into their own modules.

The approach I took here is a combination of what can be found [here in ripgrep](https://github.com/BurntSushi/ripgrep/blob/1b2c1dc67583d70d1d16fc93c90db80bead4fb09/crates/core/app.rs) and [here in cargo](https://github.com/rust-lang/cargo/tree/master/src/bin/cargo).

_Going forward:_
There's a lot to look at here. **I'm completely fine with closing this PR.** However, if anyone is interested in these kind of changes I'd be happy to try to roll out the spirit of this PR incrementally over a few PRs/commits. Again, this might just be a design/opinion nitpick at this point and may not represent any value to you all. Hope this help :)

**Comment by EverlastingBugstopper** [comment]
Hey @ericdeansanchez - I think this is something we will definitely want to do, but unfortunately I think we let this PR get a little too stale to take it anywhere.

The clap developers are working on clap v3 which will actually pull in `structopt` functionality that should let us refactor things to be less stringly typed. I think we'll wait until that comes out to revisit this.

I really appreciate your understanding and patience on this one 😄

**Comment by ericdeansanchez** [comment]
Yeah of course, and thank you! 

And oh really... that’s really exciting I haven’t been following clap v3, but I’m definitely a huge fan of less-stringly-typed code/APIs. 

Totally makes sense to wait, appreciate your time.

**Pull request closed without merging**
