### PR TITLE
Removes fixture dir if exists

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**
When running tests and creating directories, it's possible the dir already exists. If this is the case, remove it before creating the file.

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
this looks good to me but i am not sure if i'm thinking through the issues this could potenitally cause so also tagged in @ashleymichal

**Comment by ashleymichal** [comment]
i think we should look deeper at why this issue is happening in the first place. i'll have a look.

**Comment by EverlastingBugstopper** [comment]
```
---- it_can_preview_rust_project stdout ----
Created fixture at /var/folders/xw/4ttxd3d12t79cv0cb78gwhzc0000gn/T/.tmpqULEFM
thread 'it_can_preview_rust_project' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/libcore/result.rs:1187:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libstd/io/mod.rs:1412
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:141
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:202
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  13: rust_begin_unwind
             at src/libstd/panicking.rs:302
  14: std::panicking::begin_panic
  15: std::panicking::begin_panic
  16: core::result::Result<T,E>::unwrap
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/result.rs:955
  17: preview::fixture::Fixture::create_dir
             at tests/fixture/mod.rs:56
  18: preview::it_can_preview_rust_project
             at tests/preview.rs:88
  19: preview::it_can_preview_rust_project::{{closure}}
             at tests/preview.rs:53
  20: core::ops::function::FnOnce::call_once
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/ops/function.rs:227
  21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/liballoc/boxed.rs:942
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  23: std::panicking::try
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libstd/panicking.rs:265
  24: std::panic::catch_unwind
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libstd/panic.rs:395
  25: test::run_test_in_process
             at src/libtest/lib.rs:570
  26: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:473
```

this is the line: https://github.com/cloudflare/wrangler/pull/849/files#diff-076c1db94150296d69d70557d7bd01a0R293

**Comment by EverlastingBugstopper** [comment]
turns out i forgot how to merge conflicts

**Pull request closed without merging**
