### PR TITLE
Fix preview subcommand when package has dashes on its name

### PR DESCRIPTION
**Pull request by jaysonsantos**
Hey there, when trying to run wrangler preview on version  0.1.0 installed with cargo
1.35.0-nightly (0e35bd8af 2019-03-13) it will break with the following
error:
```
wrangler preview
🌀 Compiling your project to WebAssembly...
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
warning: unused manifest key: package.author
    Finished release [optimized] target(s) in 0.10s
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 0.25s
[INFO]: 📦   Your wasm pkg is ready to publish at ./pkg.
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

because the package name generated by `wrangler generate` is called `wasm-worker` and on pkg folder only `wasm_worker.js` can be found.

To better show the user what failed I also put a context to show what happened.
The fix probably is not ideal, let me know if I can make it better.

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hey @jaysonsantos ! this is great- and fixes #36 ! if you have a second i believe this is failing on `cargo fmt`- you can run and commit --amend, or i can take it over for you if you'd like. thanks so much for this contribution. i'm happy to cut a point release to get this fix in :)

**Comment by jaysonsantos** [comment]
Hi, my bad, I just did an amend to the last commit.

**Comment by ashleygwilliams** [comment]
no worries @jaysonsantos ! i hadn't documented that we were enforcing cargo fmt on CI~ i'll make sure to do that. thank you so much for contributing!!

**Comment by jaysonsantos** [comment]
What do you think about having something like [pre-commit](https://pre-commit.com/)?

**Pull request merged**
