### PR TITLE
Fix redundant "Error: " specified in #668.

### PR DESCRIPTION
**Pull request by vypr**
I believe this is the only place where such a bug occurs. Mentoring appreciated. :)

### CODE REVIEW

**Comment by gabbifish** [comment]
Thanks for your contribution, @vypr! First things first, let's make sure CI is happy with these changes. It looks like you're missing a `)` in your change to the if statement. :)

**Comment by vypr** [comment]
To think I've been doing this as a hobby for 12 years. Thanks for the heads up.

**Comment by gabbifish** [comment]
Hi @vypr! Thank you for your patience! So, upon further inspection, it looks like this duplicate print actually lives in our Rust code, not in the JS in this PR: in #668, the duplicate print occurs when calling to an API endpoint that is only called by our rust code. If you'd like, you can take this opportunity to fix this problem within our Rust code, and I'd be happy to continue providing feedback! This may be a good place to start: https://github.com/cloudflare/wrangler/blob/master/src/commands/kv/mod.rs#L78-L99

**Comment by vypr** [comment]
I'll take a look, thanks again!

**Comment by gabbifish** [comment]
Hi @vypr! Just checking in--have you had a chance to further explore this issue? No worries if not! :D

I'm also planning to close this PR for now, given that it touches javascript code ultimately not related to the issue at hand.

Do let us know if we can help you!

**Pull request closed without merging**
