### PR TITLE
fix(installer): bump version

### PR DESCRIPTION
**Pull request by ashleygwilliams**

### CODE REVIEW

**Comment by michaelb5500** [comment]
Hi Ashly I hope you read previous email 
I’m not sure if I sent it come to think of it. 
I was attempting to when all he’ll broke 
lose! My phone has a G bug and it’s been 
hard to get mail sent and so on so forth 
Did you have any things in particular that you think I should be informed of please email me. I’m shore I could learn a thing or two from you! Where did you get wrangler?
I think I have one in my device! I thought 
Wrangler was a pair of 👖 until yesterday.
Are you still working on the project?
Many thanks 
Michael Bailey

**Comment by michaelb5500** [comment]
image

**Comment by swisster4** [comment]
Do you know u are babitikas

**Comment by swisster4** [comment]
Stop sending

**Pull request merged**
